markdown: kramdown

url: "https://www.asso-lechantier-bedee.fr"
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

title: Le Chantier
description: "Association à Bédée - Culture, lien social et développement durable : Pré en Bulles, KBaBD, Festi'Bulle"

# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: Le Chantier, Bédée, Association, Pré en Bulles, Festival BD, Bande Dessinée, KBaBD, AMAP, Circuits Courts, Festi'Bulle, Guinguette
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/coccinelle.jpg

email: contact@asso-lechantier-bedee.fr
facebook_username: 
twitter_username: 
instagram_username: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-redirect-from 

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
